# DOGHOUSE
DOGHOUSE_WEIGHT_DTPIN = 27
DOGHOUSE_WEIGHT_SCKPIN = 17
DOGHOUSE_REFERENCE_UNIT = -26

# FEEDER
FEEDER_PIN = 26
FEEDER_PORTIONS = 10
FEEDER_THRESHOLD = 60

# FOOD WEIGHT
FOOD_WEIGHT_DTPIN1 = 19
FOOD_WEIGHT_SCKPIN1 = 13
FOOD_WEIGHT_DTPIN2 = 23
FOOD_WEIGHT_SCKPIN2 = 24
FOOD_WEIGHT_REFERENCE_UNIT = 390
FOOD_WEIGHT_CONFIG_RANGE = 10

# WATER WEIGHT
WATER_WEIGHT_DTPIN = 5
WATER_WEIGHT_SCKPIN = 6
WATER_WEIGHT_REFERENCE_UNIT = -415

# DOGHOUSE TEMPERATURE AND HUMIDITY
HUM_TEMP_PIN = 22
HUM_TEMP_REFERENCE_UNIT = -1.2


# SERVER
HOST_ITER_DELTA_SEC = 10

# CLIENT
HOST_IP = "10.100.102.5"
HOST_PORT = 65432

